# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 00:30:20 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: varscan, revision: 6, authored by: alice.yu
# https://precision.fda.gov/apps/app-Bz3fZfj0vqq7qkzf1Z96P91v

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Install app-specific Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	default-jre

# Download app assets
RUN curl https://dl.dnanex.us/F/D/5zqY7Q31PXzBpq6XgvF3b6q6jfbbQ79FG2v5qyKZ/VarScan%202.4.2.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"variant\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"variant\\ file\\\",\\\"help\\\":\\\"A\\ file\\ of\\ SNPs\\ or\\ indels\\ in\\ VarScan-native\\ or\\ VCF\\ format\\\"\\},\\{\\\"name\\\":\\\"readcount\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"readcount\\ file\\\",\\\"help\\\":\\\"The\\ output\\ file\\ from\\ bam-readcount\\ for\\ those\\ positions\\\"\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"output\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"output\\ file\\\",\\\"help\\\":\\\"output\\ file\\ from\\ varscan\\\"\\},\\{\\\"name\\\":\\\"filtered\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"filtered\\ file\\\",\\\"help\\\":\\\"filtered\\ file\\ from\\ varscan\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-8\\\"\\},\\\"assets\\\":\\[\\\"file-Bz3bgFj0ZXQxj2vg9Zb716xJ\\\"\\],\\\"packages\\\":\\[\\\"default-jre\\\"\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"java\\ -jar\\ /VarScan.v2.4.2.jar\\ fpfilter\\ \\$variant_path\\ \\$readcount_path\\ --output-file\\ \\$variant_prefix.output.txt\\ --filtered-file\\ \\$variant_prefix.filtered.txt\\\\nemit\\ output\\ \\$variant_prefix.output.txt\\\\nemit\\ filtered\\ \\$variant_prefix.filtered.txt\\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work